### ISSUE TITLE
Set up application database

### ISSUE THREAD

**Issue by djperrefort** [pitt-crc/Node-Nanny#10]
Working against SQLite in development is fine. However, I'd ultimately like to deploy against something like postgres.

Some questions:
1. Does the CRC operate a dedicated VM for every **CRC** database or a single VM with multiple databases on that VM? 
1. Depending on the answer to the above, do we have a VM already running where we can add databases?

Maybe someone from @pitt-crc/pitt-it has answers to the above?

Implementation of the database schema will be handled by the application itself. I just need to know where to point the app.

**Comment by buttermutter** [comment]
We don't have a defined policy other than a tendency to use a vm per application stack, whether or not it contains a database.  Aside from slurmdb I can't think of a vm dedicated only to database hosting; other (app specific) databases tend to be small and colocated with the rest of their stack.

So no, we don't currently have a dedicated database hosting vm.  Would you like one?

**Comment by djperrefort** [comment]
Having a single VM per application stack is fine. I mostly asked about a central server because if it existed I could set up a new database without adding more work to your desk. 

Can you please set up a VM with postgres? How about `usage-monitor` as the name?

No immediate rush on this.
