### ISSUE TITLE
Enable Codacy

### ISSUE THREAD

**Issue by djperrefort** [pitt-crc/Node-Nanny#13]
I'd like to enable the Codacy inspection tool for this repository. I've been using it more in other repositories and I find it helps catch things I've missed and maintain a consistent design.

@Comeani Here is an example for the [wrappers repo codacy dashboard](https://app.codacy.com/gh/pitt-crc/wrappers/dashboard) (you should be able to log in with your GitHub credentials but if not I may have to click a button somewhere). If you're in agreement, I'll enable the tool for this repo.

**Comment by Comeani** [comment]
This sounds good to me, I could certainly use the automated first pass of feedback on code I contribute. I have access to the linked dashboard page.

**Comment by djperrefort** [comment]
Great. I'll get it set up.
